### ISSUE TITLE
Patternが成功して、かつタグクラウドに存在している場合のみ有効の条件

### ISSUE THREAD

**Issue by unaunagi** [syusui-s/PixivAutoTag.user.js#4]

**Comment by unaunagi** [comment]
ソート用に記号をつけたりしているので、それをPatternで書こうと思ったのですが
Pattern _~1 (.*)
と書いても全てのタグに先頭にアンダーバーが付くだけなので、これがタグとして登録済みの場合だけ効くようにしたいです。
よろしくおねがいします。

**Comment by syusui-s** [comment]
@unaunagi 
`pattern` だと、無条件に追加してしまうのでそうなってしまいますね...
今の所は新しい文法を入れることを考えています。
アンダーバーを付加する以外の活用例や汎用的な文法を探しているのですが、
何か知っていたら教えていただけると助かります。

**Comment by unaunagi** [comment]
すみません、返信に気づいてませんでした。

http://www.mi210.com/weblog/web/tags_48.html
だいたいこのサイトで紹介されているような使い方をしています。
タグの先頭に１文字の記号を付けるパターンと、タグ全体を対になった括弧でくくるパターンです。全角のも半角のもあります。
文字順でソートした時の並びを整理が主目的なので、末尾等に付けたことはないです。
